### ISSUE TITLE
Section add and its Data Table

### ISSUE THREAD

**Issue by rashed21** [swahid/javabase-apps-school#4]
Shift combo is ok, but select class combo value will come from **classOnShift** table only that class which is added under selected shift and has an active flag.  We will prevent duplicate value added. Edit option have to add with class changes and same time we will use active or inactive flag as a **replace of delete**. 

Data will show on datatable with **shift, class and Section** name. it will also change after combo value changes.   Present table column is not ok.

**Comment by swahid** [comment]
resolve on section page combo by relation shift>Class

**Comment by swahid** [comment]
added two column className and shift name and save
